In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("imdb_top_movies_1980_2026.csv")

In [16]:
df = df.drop(columns="original_title")

In [20]:
df

,imdb_id,title,year,runtime_minutes,genres,average_rating,num_votes,imdb_url
0,tt0111161,The Shawshank Redemption,1994,142.0,Drama,9.3,3182733,https://www.imdb.com/title/tt0111161
1,tt0468569,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984,https://www.imdb.com/title/tt0468569
2,tt1375666,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,2811692,https://www.imdb.com/title/tt1375666
3,tt0137523,Fight Club,1999,139.0,"Crime,Drama,Thriller",8.8,2601984,https://www.imdb.com/title/tt0137523
4,tt0816692,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.7,2521607,https://www.imdb.com/title/tt0816692
...,...,...,...,...,...,...,...,...
16247,tt3544218,Belgica,2016,127.0,Drama,6.7,5001,https://www.imdb.com/title/tt3544218
16248,tt0101733,Dil Hai Ki Manta Nahin,1991,154.0,"Adventure,Comedy,Drama",7.2,5001,https://www.imdb.com/title/tt0101733
16249,tt10994688,The Binge,2020,98.0,Comedy,5.3,5000,https://www.imdb.com/title/tt10994688
16250,tt0263743,Billionaire,1987,96.0,"Comedy,Drama",7.5,5000,https://www.imdb.com/title/tt0263743
16251,tt1921078,Saint Petersburg,2010,120.0,"Comedy,Crime,Drama",6.4,5000,https://www.imdb.com/title/tt1921078

In [18]:
df.isna().sum()

imdb_id            0
title              0
year               0
runtime_minutes    1
genres             6
average_rating     0
num_votes          0
imdb_url           0
dtype: int64

In [19]:
df.dropna()

,imdb_id,title,year,runtime_minutes,genres,average_rating,num_votes,imdb_url
0,tt0111161,The Shawshank Redemption,1994,142.0,Drama,9.3,3182733,https://www.imdb.com/title/tt0111161
1,tt0468569,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984,https://www.imdb.com/title/tt0468569
2,tt1375666,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,2811692,https://www.imdb.com/title/tt1375666
3,tt0137523,Fight Club,1999,139.0,"Crime,Drama,Thriller",8.8,2601984,https://www.imdb.com/title/tt0137523
4,tt0816692,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.7,2521607,https://www.imdb.com/title/tt0816692
...,...,...,...,...,...,...,...,...
16247,tt3544218,Belgica,2016,127.0,Drama,6.7,5001,https://www.imdb.com/title/tt3544218
16248,tt0101733,Dil Hai Ki Manta Nahin,1991,154.0,"Adventure,Comedy,Drama",7.2,5001,https://www.imdb.com/title/tt0101733
16249,tt10994688,The Binge,2020,98.0,Comedy,5.3,5000,https://www.imdb.com/title/tt10994688
16250,tt0263743,Billionaire,1987,96.0,"Comedy,Drama",7.5,5000,https://www.imdb.com/title/tt0263743
16251,tt1921078,Saint Petersburg,2010,120.0,"Comedy,Crime,Drama",6.4,5000,https://www.imdb.com/title/tt1921078

Potential Questions:
- most popular genres
- does length of movie affect its rating
- which year had the longest movies