In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("imdb_top_movies_1980_2026.csv")

In [3]:
df

,imdb_id,title,original_title,year,runtime_minutes,genres,average_rating,num_votes,imdb_url
0,tt0111161,The Shawshank Redemption,The Shawshank Redemption,1994,142.0,Drama,9.3,3182733,https://www.imdb.com/title/tt0111161
1,tt0468569,The Dark Knight,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984,https://www.imdb.com/title/tt0468569
2,tt1375666,Inception,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,2811692,https://www.imdb.com/title/tt1375666
3,tt0137523,Fight Club,Fight Club,1999,139.0,"Crime,Drama,Thriller",8.8,2601984,https://www.imdb.com/title/tt0137523
4,tt0816692,Interstellar,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.7,2521607,https://www.imdb.com/title/tt0816692
...,...,...,...,...,...,...,...,...,...
16247,tt3544218,Belgica,Belgica,2016,127.0,Drama,6.7,5001,https://www.imdb.com/title/tt3544218
16248,tt0101733,Dil Hai Ki Manta Nahin,Dil Hai Ki Manta Nahin,1991,154.0,"Adventure,Comedy,Drama",7.2,5001,https://www.imdb.com/title/tt0101733
16249,tt10994688,The Binge,The Binge,2020,98.0,Comedy,5.3,5000,https://www.imdb.com/title/tt10994688
16250,tt0263743,Billionaire,Milyarder,1987,96.0,"Comedy,Drama",7.5,5000,https://www.imdb.com/title/tt0263743
16251,tt1921078,Saint Petersburg,San Peterzburg,2010,120.0,"Comedy,Crime,Drama",6.4,5000,https://www.imdb.com/title/tt1921078

In [4]:
df.shape

(16252, 9)

In [5]:
df.dtypes

imdb_id             object
title               object
original_title      object
year                 int64
runtime_minutes    float64
genres              object
average_rating     float64
num_votes            int64
imdb_url            object
dtype: object

In [6]:
df = df.drop(columns=["original_title", "imdb_url"])

In [7]:
df.isna().sum()

imdb_id            0
title              0
year               0
runtime_minutes    1
genres             6
average_rating     0
num_votes          0
dtype: int64

In [8]:
df.dropna()

,imdb_id,title,year,runtime_minutes,genres,average_rating,num_votes
0,tt0111161,The Shawshank Redemption,1994,142.0,Drama,9.3,3182733
1,tt0468569,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984
2,tt1375666,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,2811692
3,tt0137523,Fight Club,1999,139.0,"Crime,Drama,Thriller",8.8,2601984
4,tt0816692,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.7,2521607
...,...,...,...,...,...,...,...
16247,tt3544218,Belgica,2016,127.0,Drama,6.7,5001
16248,tt0101733,Dil Hai Ki Manta Nahin,1991,154.0,"Adventure,Comedy,Drama",7.2,5001
16249,tt10994688,The Binge,2020,98.0,Comedy,5.3,5000
16250,tt0263743,Billionaire,1987,96.0,"Comedy,Drama",7.5,5000
16251,tt1921078,Saint Petersburg,2010,120.0,"Comedy,Crime,Drama",6.4,5000

In [9]:
df

,imdb_id,title,year,runtime_minutes,genres,average_rating,num_votes
0,tt0111161,The Shawshank Redemption,1994,142.0,Drama,9.3,3182733
1,tt0468569,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984
2,tt1375666,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,2811692
3,tt0137523,Fight Club,1999,139.0,"Crime,Drama,Thriller",8.8,2601984
4,tt0816692,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.7,2521607
...,...,...,...,...,...,...,...
16247,tt3544218,Belgica,2016,127.0,Drama,6.7,5001
16248,tt0101733,Dil Hai Ki Manta Nahin,1991,154.0,"Adventure,Comedy,Drama",7.2,5001
16249,tt10994688,The Binge,2020,98.0,Comedy,5.3,5000
16250,tt0263743,Billionaire,1987,96.0,"Comedy,Drama",7.5,5000
16251,tt1921078,Saint Petersburg,2010,120.0,"Comedy,Crime,Drama",6.4,5000

Potential Questions:
- ROBERT AND MATTHEW: trends of most popular genres per year
- EVELYN AND ALEX: does rating of movies change over time?
- STEPHANIE AND ISAURO: which movies have most votes and does that it affect its average_rating?

In [ ]:
# ROBERT AND MATTHEW: trends of most popular genres per year

In [ ]:
# EVELYN AND ALEX: does rating of movies change over time?

In [ ]:
# STEPHANIE AND ISAURO: which movies have most votes and does that it affect its average_rating?